// <auto-generated />
using System;
using CWA.TestResultsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CWA.TestResultsService.Migrations
{
    [DbContext(typeof(LabTestResultsDBContext))]
    [Migration("20200512123510_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CWA.TestResultsService.Models.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnName("notification_date")
                        .HasColumnType("datetime");

                    b.Property<string>("NotificationPlatform")
                        .HasColumnName("notification_platform")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("NotificationToken")
                        .HasColumnName("notification_token")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("Result")
                        .HasColumnName("result")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnName("result_date")
                        .HasColumnType("datetime");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasColumnName("result_id")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .IsUnique()
                        .HasName("IX_test_results");

                    b.ToTable("test_results");
                });
#pragma warning restore 612, 618
        }
    }
}
