// <auto-generated />
using System;
using CWA.TestResultsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CWA.TestResultsService.Migrations
{
    [DbContext(typeof(LabTestResultsDBContext))]
    [Migration("20200526101104_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CWA.TestResultsService.Models.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnName("result")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnName("result_date")
                        .HasColumnType("timestamp");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasColumnName("result_id")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .IsUnique()
                        .HasName("IX_test_results");

                    b.ToTable("test_results");
                });
#pragma warning restore 612, 618
        }
    }
}
