spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  ssl:
    enabled: true
    key-store-password: ${SSL_TESTRESULT_KEYSTORE_PASSWORD}
    trust-store-password: ${SSL_TESTRESULT_TRUSTSTORE_PASSWORD}
