// <auto-generated />
using System;
using Covid19LabResultsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19LabResultsService.Migrations
{
    [DbContext(typeof(LabTestResultsDBContext))]
    partial class LabTestResultsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Covid19LabResultsService.Models.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Result")
                        .HasColumnName("result")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnName("result_date")
                        .HasColumnType("datetime");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasColumnName("result_id")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .IsUnique()
                        .HasName("IX_test_results");

                    b.ToTable("test_results");
                });
#pragma warning restore 612, 618
        }
    }
}
